In [24]:
import pandas as pd
import numpy as np

import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split

In [25]:
iris = datasets.load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target)
y.columns = ['labels']

In [28]:
import math

def euclideanDistance(instance1, instance2, length):
    distance = 0
    for x in range(length):
        distance += pow(instance1[x]-instance2[x], 2)
    return math.sqrt(distance)

In [29]:
data1=[2, 3, 4, 'a']
data2=[4, 6, 8, 'b']

euclideanDistance(data1, data2, 3)

5.385164807134504

In [30]:
range(3)

range(0, 3)

In [31]:
import operator

def getNeighbors(trainSet, testInstance, k):
    distances=[]
    length = len(testInstance) - 1 
    for x in range(len(trainSet)):
        dist = euclideanDistance(testInstance, trainSet[x], length)
#         print(dist)
        distances.append((trainSet[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

In [32]:
trainSet = [[2, 3, 4, 'a'], [4, 6, 8, 'b']]
testInstance = [5, 5, 5]
getNeighbors(trainSet, testInstance, 1)

[[4, 6, 8, 'b']]

In [33]:
# Response

def getResponse(neighbors):
    classVotes = {}
    for x in range(len(neighbors)):
        response = neighbors[x][-1]
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    sortedVotes =sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)
    return sortedVotes[0][0]

In [34]:
neighbors = [[1, 1, 1, 'a'], [2, 2, 2, 'a'],[3, 3, 3, 'b']]
getResponse(neighbors)

'a'

In [35]:
def getAccuracy(testSet, predictions):
    correct = 0
    for x in range(len(testSet)):
        if testSet[x][-1] is predictions[x]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [36]:
testSet = [[1, 1, 1, 'a'], [2, 2, 2, 'a'],[3, 3, 3, 'b']]
predictions = ['a', 'a', 'a']
accuracy = getAccuracy(testSet, predictions)
accuracy

66.66666666666666

In [37]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=.2, random_state=50)

In [38]:
X_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
125                7.2               3.2                6.0               1.8
98                 5.1               2.5                3.0               1.1
73                 6.1               2.8                4.7               1.2
144                6.7               3.3                5.7               2.5
21                 5.1               3.7                1.5               0.4

In [39]:
y_test.head()

labels
88        1
72        1
20        0
16        0
147       2

In [40]:
X_test.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
88                 5.6               3.0                4.1               1.3
72                 6.3               2.5                4.9               1.5
20                 5.4               3.4                1.7               0.2
16                 5.4               3.9                1.3               0.4
147                6.5               3.0                5.2               2.0

In [41]:
test_set = pd.concat([X_test, y_test], axis=1).values
len(test_set)

30

In [42]:
train_set = pd.concat([X_train, y_train], axis=1).values
len(train_set)

120

In [43]:
pd.concat([X_test, y_test], axis=1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
88                 5.6               3.0                4.1               1.3   
72                 6.3               2.5                4.9               1.5   
20                 5.4               3.4                1.7               0.2   
16                 5.4               3.9                1.3               0.4   
147                6.5               3.0                5.2               2.0   
140                6.7               3.1                5.6               2.4   
113                5.7               2.5                5.0               2.0   
23                 5.1               3.3                1.7               0.5   
12                 4.8               3.0                1.4               0.1   
68                 6.2               2.2                4.5               1.5   
39                 5.1               3.4                1.5               0.2   
130                7.4               2.8                6.1               1.9   
34                 4.9               3.1                1.5               0.2   
112                6.8               3.0                5.5               2.1   
55                 5.7               2.8                4.5               1.3   
25                 5.0               3.0                1.6               0.2   
82                 5.8               2.7                3.9               1.2   
48                 5.3               3.7                1.5               0.2   
81                 5.5               2.4                3.7               1.0   
77                 6.7               3.0                5.0               1.7   
100                6.3               3.3                6.0               2.5   
80                 5.5               2.4                3.8               1.1   
14                 5.8               4.0                1.2               0.2   
131                7.9               3.8                6.4               2.0   
86                 6.7               3.1                4.7               1.5   
118                7.7               2.6                6.9               2.3   
56                 6.3               3.3                4.7               1.6   
54                 6.5               2.8                4.6               1.5   
97                 6.2               2.9                4.3               1.3   
143                6.8               3.2                5.9               2.3   

     labels  
88        1  
72        1  
20        0  
16        0  
147       2  
140       2  
113       2  
23        0  
12        0  
68        1  
39        0  
130       2  
34        0  
112       2  
55        1  
25        0  
82        1  
48        0  
81        1  
77        1  
100       2  
80        1  
14        0  
131       2  
86        1  
118       2  
56        1  
54        1  
97        1  
143       2

In [44]:
k = 3
predictions = []

print('Train Set: ' + repr(len(train_set)))
print('Test Set: '+ repr(len(test_set)))
for x in range(len(test_set)):
    neighbors = getNeighbors(train_set, test_set[x],k)
    result = getResponse(neighbors)
    predictions.append(result)
    print('> predicted=' + repr(result) + ', actual=' + repr(test_set[x][-1]))
accuracy = getAccuracy(test_set, predictions)
accuracy
# print('Accuracy: '+ repr(accuracy) + '%')

Train Set: 120
Test Set: 30
> predicted=1.0, actual=1.0
> predicted=2.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=2.0, actual=2.0
> predicted=2.0, actual=2.0
> predicted=2.0, actual=2.0
> predicted=0.0, actual=0.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=2.0, actual=2.0
> predicted=0.0, actual=0.0
> predicted=2.0, actual=2.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=2.0, actual=2.0
> predicted=1.0, actual=1.0
> predicted=0.0, actual=0.0
> predicted=2.0, actual=2.0
> predicted=1.0, actual=1.0
> predicted=2.0, actual=2.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=1.0, actual=1.0
> predicted=2.0, actual=2.0


0.0

In [45]:
test_set

array([[5.6, 3. , 4.1, 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [6.5, 3. , 5.2, 2. , 2. ],
       [6.7, 3.1, 5.6, 2.4, 2. ],
       [5.7, 2.5, 5. , 2. , 2. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [7.4, 2.8, 6.1, 1.9, 2. ],
       [4.9, 3.1, 1.5, 0.2, 0. ],
       [6.8, 3. , 5.5, 2.1, 2. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5.8, 2.7, 3.9, 1.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 0. ],
       [5.5, 2.4, 3.7, 1. , 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [7.7, 2.6, 6.9, 2.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [6.8, 3

In [46]:
predictions

[1.0,
 2.0,
 0.0,
 0.0,
 2.0,
 2.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 2.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 2.0,
 1.0,
 0.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0]

In [49]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [50]:
y_pred = classifier.predict(X_test)

In [51]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 9  0  0]
 [ 0 11  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.92      0.96        12
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [1]:
11/(11+1+0)

0.9166666666666666